package Model;

public enum ItemType {
	STICK, ROCK, PLANK, LEAF, MUD, GRASS, CLOTH, LIFEJACKET, SNACK, BRICK, SPEAR, VINE, CORPSE, FIRESTICK, MEAT, ARTIFACT, BERRIES, AXE, WEB, SAIL, METAL, OIL, WATER
}