package deserted.model.item;

public enum ItemType {
	FISH, STICK, ROCK, PLANK, LEAF, MUD, GRASS, CLOTH, LIFEJACKET, SNACK, BRICK, SPEAR, VINE, CORPSE, FIRESTICK, MEAT, ARTIFACT, BERRIES, AXE, WEB, SAIL, METAL, OIL, WATER, FLIGHT, SEAWATER, RAFT, BOAT, PLANE, SPACESHIP
}